# Generated by Django 5.1 on 2024-09-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('eliminado', 'Eliminado')], default='activo', max_length=15, null=True),
        ),
    ]
