# Generated by Django 5.1 on 2024-09-02 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='state',
            field=models.CharField(choices=[('publicado', 'PUBLICADO'), ('revision', 'REVISION'), ('eliminado', 'ELIMINADO'), ('suspendido', 'SUSPENDIDO')], max_length=10, null=True, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto_positivo', models.BooleanField(default=True)),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.descuento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
